---
apiVersion: v1
kind: Namespace
metadata:
  name: awscli

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: awscli
  namespace: awscli

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aws-access
  namespace: awscli

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: awscli
  namespace: awscli
roleRef:
  kind: Role
  name: aws-access
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: awscli

---
apiVersion: v1
kind: Pod
metadata:
  name: awscli
  namespace: awscli
  labels:
    app: awscli
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"    
spec:
  serviceAccountName: awscli
  securityContext:
    runAsNonRoot: true
    supplementalGroups: [ 10001] 
    fsGroup: 10001
  containers:
    - name: awscli
      image: andreswebs/awscli
      imagePullPolicy: Always
      securityContext:
        runAsUser: 1000
      stdin: true
      tty: true
      env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
