---
apiVersion: v1
kind: Namespace
metadata:
  name: awscli

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: awscli
  namespace: awscli

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aws-access
  namespace: awscli

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: awscli
  namespace: awscli
roleRef:
  kind: Role
  name: aws-access
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: awscli

---
apiVersion: v1
kind: Pod
metadata:
  name: awscli
  namespace: awscli
spec:
  serviceAccountName: awscli
  containers:
    - name: awscli
      image: andreswebs/awscli
      imagePullPolicy: Always
      stdin: true
      tty: true
      env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
